image: maven:3.6.3-jdk-11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - export KUBECONFIG=$(pwd)/kubeconfig.yml
    - kubectl apply -f deployment.yml
    - kubectl apply -f service.yml
    - kubectl rollout status deployment/my-app
  environment:
    name: production
  only:
    - master
  dependencies:
    - build

