apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: <image-repository>/my-app:<version>
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          value: "<comma-separated-list-of-kafka-brokers>"
