apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://<aws-cluster-endpoint>:<port>
    certificate-authority-data: <base64-encoded-cluster-certificate>
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
current-context: my-context
users:
- name: my-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "<cluster-name>"
